name: Update Cloudreve Binary

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "gopcn"
          git config --global user.email "121377609+gopcn@users.noreply.github.com"

      - name: Get latest release
        id: get-latest-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: cloudreve/Cloudreve
          excludes: prerelease, draft
          token: ${{ secrets.AUTH_PAT }}

      - name: Download and Extract Cloudreve
        run: |
          curl -sL "https://github.com/cloudreve/Cloudreve/releases/download/${{ steps.get-latest-release.outputs.release }}/cloudreve_${{ steps.get-latest-release.outputs.release }}_linux_amd64.tar.gz" | tar -zxv

      - name: Commit Changes
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.AUTH_PAT }}
          commit-message: "v${{ steps.get-latest-release.outputs.release }}"
          files: cloudreve
          rebase: 'true'
          name: gopcn
          email: 121377609+gopcn@users.noreply.github.com