name: Update Cloudreve Binary

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and Extract Cloudreve
        run: |
          repo="cloudreve/Cloudreve"
          releases=$(curl -s "https://api.github.com/repos/$repo/releases")
          tag=$(echo "$releases" | jq -r '.[] | select(.prerelease == false) | .tag_name' | head -n 1)
          download_url="https://github.com/$repo/releases/download/$tag/cloudreve_${tag}_linux_amd64.tar.gz"
          echo "Downloading $download_url"
          wget "$download_url" -O cloudreve.tar.gz
          tar -xzf cloudreve.tar.gz
          mv cloudreve cloudreve_tmp

          version="${tag#v}"
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config --global user.name "gopcn"
          git config --global user.email "121377609+gopcn@users.noreply.github.com"
          git checkout main

      - name: Preserve repository README.md and Remove unnecessary files
        run: |
          mv README.md README_tmp.md
          rm -f LICENSE README_zh-CN.md README.md

      - name: Restore repository README.md
        run: |
          mv README_tmp.md README.md

      - name: Restore original README.md content
        run: |
          git restore README.md

      - name: Rename Cloudreve binary and Commit changes
        run: |
          mv cloudreve_tmp cloudreve
          rm cloudreve.tar.gz
          git add .
          git diff-index --quiet HEAD || git commit -m "Version $VERSION"
          git push origin main